const pharmacies = [
  {
    name: 'Apollo Pharmacy T Nagar',
    type: 'pharmacy',
    address: 'Pondy Bazaar, T Nagar, Chennai 600017',
    city: 'Chennai',
    area: 'T Nagar',
    latitude: 13.0418,
    longitude: 80.2337,
    medicines: ['Paracetamol 650', 'Cetirizine', 'ORS Sachet', 'Salbutamol Inhaler'],
    phone: '+91 98400 10017',
    workingHours: '8 AM - 11 PM',
    open24Hours: false,
    emergencyService: true
  },
  {
    name: 'MedPlus Anna Nagar',
    type: 'medical_store',
    address: '2nd Avenue, Anna Nagar, Chennai 600040',
    city: 'Chennai',
    area: 'Anna Nagar',
    latitude: 13.085,
    longitude: 80.2101,
    medicines: ['Crocin 650', 'Ibuprofen', 'Amoxicillin 500', 'ORS Sachet'],
    phone: '+91 98400 20040',
    workingHours: '7 AM - 10 PM',
    open24Hours: false,
    emergencyService: false
  },
  {
    name: 'Guardian Pharmacy Velachery',
    type: 'pharmacy',
    address: '100 Feet Bypass Road, Velachery, Chennai 600042',
    city: 'Chennai',
    area: 'Velachery',
    latitude: 12.9759,
    longitude: 80.2205,
    medicines: ['Dolo 650', 'Levocetirizine', 'Budesonide Respules', 'Aceclofenac'],
    phone: '+91 98400 30042',
    workingHours: '8 AM - 11 PM',
    open24Hours: false,
    emergencyService: true
  },
  {
    name: 'Care Point Pharmacy Ambattur',
    type: 'medical_store',
    address: 'MTH Road, Ambattur, Chennai 600053',
    city: 'Chennai',
    area: 'Ambattur',
    latitude: 13.1143,
    longitude: 80.1548,
    medicines: ['Paracetamol 650', 'Cetzine', 'Amoxicillin 500', 'Electral Powder'],
    phone: '+91 98400 40053',
    workingHours: '9 AM - 10 PM',
    open24Hours: false,
    emergencyService: false
  },
  {
    name: 'OMR Health Pharmacy Sholinganallur',
    type: 'pharmacy',
    address: 'OMR Main Road, Sholinganallur, Chennai 600119',
    city: 'Chennai',
    area: 'Sholinganallur',
    latitude: 12.901,
    longitude: 80.2279,
    medicines: ['Crocin 650', 'Cetirizine', 'Salbutamol Inhaler', 'Diclofenac Gel'],
    phone: '+91 98400 50019',
    workingHours: 'Open all day',
    open24Hours: true,
    emergencyService: true
  },
  {
    name: 'Tambaram City Pharmacy',
    type: 'pharmacy',
    address: 'GST Road, Tambaram, Chennai 600045',
    city: 'Chennai',
    area: 'Tambaram',
    latitude: 12.9249,
    longitude: 80.1001,
    medicines: ['Dolo 650', 'Ibuprofen', 'Azithromycin 500', 'ORS Sachet'],
    phone: '+91 98400 60045',
    workingHours: '7 AM - 11 PM',
    open24Hours: false,
    emergencyService: true
  },
  {
    name: 'Apollo Hospital Greams Road',
    type: 'hospital',
    address: 'Greams Lane, Thousand Lights, Chennai 600006',
    city: 'Chennai',
    area: 'Thousand Lights',
    latitude: 13.0639,
    longitude: 80.2518,
    medicines: ['Paracetamol 650', 'Salbutamol Inhaler', 'ORS Sachet'],
    phone: '+91 98400 70006',
    workingHours: 'Open all day',
    open24Hours: true,
    emergencyService: true
  },
  {
    name: 'MGM Healthcare Aminjikarai',
    type: 'hospital',
    address: 'Nelson Manickam Road, Aminjikarai, Chennai 600029',
    city: 'Chennai',
    area: 'Aminjikarai',
    latitude: 13.0734,
    longitude: 80.2249,
    medicines: ['Crocin 650', 'Budesonide Respules', 'Ibuprofen'],
    phone: '+91 98400 80029',
    workingHours: 'Open all day',
    open24Hours: true,
    emergencyService: true
  },
  {
    name: 'City Medico Adyar',
    type: 'medical_store',
    address: 'LB Road, Adyar, Chennai 600020',
    city: 'Chennai',
    area: 'Adyar',
    latitude: 13.0012,
    longitude: 80.2565,
    medicines: ['Dolo 650', 'Cetirizine', 'Electral Powder'],
    phone: '+91 98400 90020',
    workingHours: '8 AM - 10 PM',
    open24Hours: false,
    emergencyService: false
  },
  {
    name: 'Health First Medicals Porur',
    type: 'medical_store',
    address: 'Mount Poonamallee Road, Porur, Chennai 600116',
    city: 'Chennai',
    area: 'Porur',
    latitude: 13.0385,
    longitude: 80.1565,
    medicines: ['Paracetamol 650', 'Levocetirizine', 'Aceclofenac'],
    phone: '+91 98400 91016',
    workingHours: '7 AM - 11 PM',
    open24Hours: false,
    emergencyService: false
  }
];

export default pharmacies;
